### ISSUE TITLE
problems to get your config booting

### ISSUE THREAD

**Issue by luxus** [linyinfeng/dotfiles#1]
hi,
i use ur config as a base. its pretty great compare to many other configs. very easy to understand.
i tried to make my system works but it doesn't boot (complaining about stage 1 and not be able to mount root)
any idea what I maybe did wrong?

https://github.com/luxus/dotfiles/blob/main/hosts/vanessa.nix

**Comment by linyinfeng** [comment]
Hi, my configuration is fully based on [digga](https://github.com/divnix/digga)'s [devos](https://github.com/divnix/digga/tree/main/examples/devos) template. If you are looking for a template for your configuration, I believe [devos](https://github.com/divnix/digga/tree/main/examples/devos) should be a better choice.

**Comment by luxus** [comment]
thanks lin for taking time to answer.
i can understand that you don't have the time to support people that uses your config :D
i did choose your config because you had some nice solutions in your code that I liked.
my knowledge of nixlang is not that good I code everything by myself, it's easier to learn by reading your code and deleting stuff I don't need.
i added the drives manually to my https://github.com/luxus/dotfiles/blob/luxus/hosts/vanessa.nix
instead of the function and it worked.
