### ISSUE TITLE
Replace digga depends in build-module-list

### ISSUE THREAD

**Issue by Aleksanaa** [linyinfeng/dotfiles#3]
This introduces digga depends in build-module-list:
https://github.com/linyinfeng/dotfiles/blob/347417266c9395d47734ddc7d1477ec37c4ee0e7/lib/build-module-list.nix#L8

In order to get around this, I tried to use `builtins.readDir` like this:
```nix
dir:
builtins.map (name: import (dir + "/${name}")) (builtins.attrNames
  (lib.filterAttrs (name: _: lib.hasSuffix ".nix" name) (builtins.readDir dir)))
```

I don't know if this works as intended though.

**Comment by linyinfeng** [comment]
The problem with this new function is that it only scans the first layer of the directory, while `rakeLeaves` walks into subdirectories recursively.

**Comment by Aleksanaa** [comment]
> The problem with this new function is that it only scans the first layer of the directory, while `rakeLeaves` walks into subdirectories recursively.

I'm not familiar with digga anyways... But this function works for me. If you think this has no help, just close it.
